### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by juanpi922** [coronalabs/CoronaSDK-AtomPlugin#2]

**Comment by myisaak** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-corona](https://github.com/coronalabs/CoronaSDK-AtomPlugin) package 1.0.7


### Stack Trace

Uncaught TypeError: this.element.querySelector is not a function

```
At C:\Users\Chiara\.atom\packages\autocomplete-corona\node_modules\atom-package-deps\lib\view.js:41

TypeError: this.element.querySelector is not a function
    at View.advance (/packages/autocomplete-corona/node_modules/atom-package-deps/lib/view.js:41:36)
    at /packages/autocomplete-corona/node_modules/atom-package-deps/lib/main.js:53:16
    at stdout (/packages/autocomplete-corona/node_modules/atom-package-deps/lib/helpers.js:24:11)
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/src/buffered-process.js:212:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
     -4:53.8.0 core:confirm (input.hidden-input)
     -4:12.2.0 core:backspace (input.hidden-input)
     -4:11 core:confirm (input.hidden-input)
     -3:13 core:select-all (input.hidden-input)
     -3:11.9.0 core:move-right (input.hidden-input)
  7x -3:11.5.0 core:backspace (input.hidden-input)
     -3:10.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-corona 1.0.7 
language-lua 0.9.11 
```

**Comment by juanpi922** [comment]
dont remember the steps to reproduce but already solved it, thanks anyway

**Comment by jochasinga** [comment]
This issue should be opened. As of today, I installed this plugin via Atom's package manager and as I started typing Atom threw the following error (replaced my home directory with `$HOME`):

- Atom v1.19.2
- autocomplete-corona v1.0.7
- MacOS Sierra v10.12.6


```
Uncaught TypeError: Cannot read property 'length' of undefined

${HOME}/.atom/packages/autocomplete-corona/lib/autocomplete-provider.coffee:22
```

And the stacktrace:

```

TypeError: Cannot read property 'length' of undefined
    at Object.findSuggestions (${HOME}/.atom/packages/autocomplete-corona/lib/autocomplete-provider.coffee:22:9)
    at Object.getSuggestions (${HOME}/.atom/packages/autocomplete-corona/lib/autocomplete-provider.coffee:18:10)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)

```

**Comment by coronarob** [comment]
We have had two engineers try this and we can't reproduce it. Can you provide more specifics on what you're doing to cause this? Are you typing in text? Are you deleting text? Just starting the editor? We really need a better description of the cause.

Thanks
Rob

**Comment by Shchvova** [comment]
This should be fixed if you update a plugin.
