### ISSUE TITLE
Failed to activate the autocomplete-corona package

### ISSUE THREAD

**Issue by sabmarketer** [coronalabs/CoronaSDK-AtomPlugin#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-corona](https://github.com/coronalabs/CoronaSDK-AtomPlugin) package 1.1.4

### Stack Trace

Failed to activate the autocomplete-corona package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at Object.consumeProvider (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/autocomplete-plus/lib/main.js:89:27)
    at Object.consumeProvider_2 (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/autocomplete-plus/lib/main.js:62:23)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:397:75)
    at Package.activateNow (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:233:20)
    at measure (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.25.1/resources/app/src/package-manager.js:695:42)
    at packagesToEnable.forEach.name (~/AppData/Local/atom/app-1.25.1/resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (~/AppData/Local/atom/app-1.25.1/resources/app/src/package-manager.js:440:30)
    at emitter.on (~/AppData/Local/atom/app-1.25.1/resources/app/src/config.js:1023:22)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.emitChangeEvent (~/AppData/Local/atom/app-1.25.1/resources/app/src/config.js:1175:62)
    at Config.setRawValue (~/AppData/Local/atom/app-1.25.1/resources/app/src/config.js:1008:23)
    at Config.set (~/AppData/Local/atom/app-1.25.1/resources/app/src/config.js:711:18)
    at Config.removeAtKeyPath (~/AppData/Local/atom/app-1.25.1/resources/app/src/config.js:901:16)
    at Package.enable (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:75:30)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.25.1/resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/settings-view/lib/package-card.js:362:31)
```

### Commands

```
  4x -4:31.8.0 core:move-right (input.hidden-input)
 14x -4:30.3.0 core:backspace (input.hidden-input)
     -4:23.2.0 core:move-down (input.hidden-input)
     -4:20.5.0 autocomplete-plus:confirm (input.hidden-input)
     -4:20.5.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  6x -4:18.6.0 core:move-right (input.hidden-input)
 12x -4:16.2.0 core:backspace (input.hidden-input)
     -4:05.6.0 autocomplete-plus:confirm (input.hidden-input)
     -4:05.6.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
 27x -2:51.5.0 core:backspace (input.hidden-input)
     -2:41.3.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  9x -2:27.5.0 core:backspace (input.hidden-input)
  4x -2:03.5.0 core:move-right (input.hidden-input)
     -2:02.2.0 core:backspace (input.hidden-input)
     -2:01.3.0 core:paste (input.hidden-input)
     -1:11.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-corona 1.1.4 
language-lua 0.9.11 
```

**Comment by Shchvova** [comment]
This should be fixed in latest corona.
